name: lynot-dart-flutter

packages:
  - packages/**

scripts:
  sync:
    run: dart run melos exec -c 1 "lockpick sync ./"

  fix:
    run: dart run melos exec "dart fix --apply"

  test:analyze:dart:
    run: dart run melos exec -c 1 --no-flutter "dart analyze"

  test:analyze:flutter:
    run: dart run melos exec -c 1  --flutter "flutter analyze"

  test:analyze:
    run: |
      dart run melos run test:analyze:dart
      dart run melos run test:analyze:flutter

  test:only:
    run: dart run melos exec --dir-exists="test" -c 1 "flutter test --coverage"

  test:
    run: |
      dart run melos format --set-exit-if-changed
      dart run melos run test:analyze
      dart run melos run test:only

  coverage:install:
    run: |
      npm i -g lcov-result-merger
      flutter pub global activate remove_from_coverage

  coverage:
    run: |
      lcov-result-merger "packages/**/coverage/lcov.info" coverage/lcov.info
