name: lynot-dart-flutter

packages:
  - packages/**

scripts:
  sync:
    run: melos exec -c 1 "lockpick sync ./"

  format:dart:
    run: melos exec --no-flutter "dart format ."

  format:flutter:
    run: melos exec --flutter "flutter format ."

  format:
    run: |
      melos run format:dart
      melos run format:flutter

  fix:
    run: melos exec "dart fix --apply"

  test:format:dart:
    run: melos exec --no-flutter"dart format --set-exit-if-changed ."

  test:format:flutter:
    run: melos exec --flutter --depends-on="flutter_test" "flutter format --set-exit-if-changed ."

  test:format:
    run: |
      melos run test:format:dart
      melos run test:format:flutter

  test:analyze:dart:
    run: melos exec --no-flutter "dart analyze"

  test:analyze:flutter:
    run: melos exec --flutter "flutter analyze"

  test:analyze:
    run: |
      melos run test:analyze:dart
      melos run test:analyze:flutter

  test:only:
    run: melos exec --dir-exists="test" -c 1 "flutter test --coverage"

  test:
    run: |
      melos run test:format
      melos run test:analyze
      melos run test:only

  coverage:install:
    run: |
      npm i -g lcov-result-merger
      flutter pub global activate remove_from_coverage

  coverage:
    run: |
      lcov-result-merger "packages/**/coverage/lcov.info" coverage/lcov.info
