name: riverform
description: A dart form implementation using riverpod package.
version: 0.2.0

homepage: https://github.com/lynot/lynot-dart-flutter
repository: https://github.com/lynot/lynot-dart-flutter/tree/master/packages/riverform

environment:
   sdk: ">=3.8.0 <4.0.0"

dependencies:
  async: ^2.13.0
  equatable: ^2.0.7
  riverpod: ^2.6.1

dev_dependencies:
  lint: ^2.8.0
  test: ^1.26.2
