name: flutter_riverform
description: A flutter implementation of riverform using flutter_riverpod package.
version: 0.2.0

homepage: https://github.com/lynot/lynot-dart-flutter
repository: https://github.com/lynot/lynot-dart-flutter/tree/master/packages/flutter_riverform

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  riverform: ^0.2.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.3.0
