name: flutter_lyform
description: Flutter package to implement forms in an easy, fast and effective way using the lyform and flutter_bloc packages.
version: 0.15.1
homepage: https://github.com/lynotofficial/lynot-dart-flutter
repository: https://github.com/lynotofficial/lynot-dart-flutter/tree/master/packages/flutter_lyform

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  bloc: ^9.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  lyform: ^0.15.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.3.0
  mocktail: ^1.0.4
