name: test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v5

      - name: Install Flutter
        uses: subosito/flutter-action@v2

      - name: Run Melos Bootstrap
        run: dart run melos bs

      - name: Run Tests
        run: dart run melos run test

      - name: Upload Coverage
        uses: codecov/codecov-action@v5
